# 测试222222

wsdds

## Group apicloud

#### 创建团队 [POST /api/team]

创建团队

+ Parameters

    + id

+ Request (application/x-www-form-urlencoded)

    + Headers

            Accept: application/json

    + Attributes

        + id - ID值
        + name (required) - ID值
        + members - ID值
        + owner - ID值
        + description - ID值

    + Body

            name=sit&Duis357a=&id=culpa

+ Response 200 (application/json)

    无

    + Body

            {}

    + Schema

            {
              "properties": {
                "msg": {
                  "description": "ID值",
                  "type": "string"
                },
                "result": {
                  "description": "ID值",
                  "type": "string"
                }
              },
              "type": "object"
            }

