# 新项目测试

新项目测试

## Group qew

#### 测试 [GET /api/wd]

测试

+ Parameters

    + id

    + name (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    无

    + Body