
# 云客

云客

## Group ce

### /api/ewf/ss

#### 测试文档 [POST]

完善

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "first": {
                  "properties": {
                    "second": {
                      "description": "",
                      "type": "string",
                      "default": [
                        "ARRAY<OBJECT>",
                        "{\"ce\":{\"default\":null,\"required\":false,\"description\":\"\",\"type\":\"string\"}}"
                      ]
                    }
                  },
                  "description": "",
                  "type": "object"
                }
              }
            }

+ Response 200 (application/json)

    无

    + Body
